version: '3'

services:

    web:
        build: .
        ports:
            - 8000:8000
        volumes:
            - ../db:/app/sqlite
    web2:
        build: .
        ports:
            - 9000:8000
        volumes:
            - ../db:/app/sqlite

            
