version: '3.3'

services:
    django_app:
        build: .
        volumes:
            - static:/app/static
            - .:/app
        command: python manage.py runserver localhost:8000
        ports:
            - 8000:8000


    nginx:
        image: nginx:1.13
        ports:
            - 8000:80
        volumes:
            - ./config/nginx/conf.d:etc/nginx/conf.d
            - static:/app/static
        depends_on:
            - django_app

    volumes:
        .:
        static: