# Generated by Django 3.2.4 on 2021-06-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('imagen', models.FileField(upload_to='productos')),
                ('descripcion', models.CharField(max_length=124)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(max_length=64)),
            ],
        ),
    ]
